print("hello world ! how are you") 
print("welcome to my world") 
print("hey what is your name enter below") 
name = input("what is your name?") 
print("hello" +name)
print("thankyou for submitting your name") 
print("so, let's paly a game THE AGE GAME") 
print("okhyyy! start") 
old_age= input("enter your old age:") 
print("thankyou") 
print(" i will guess you age after two year") 
new_age= int(old_age)+2
print(new_age) 
print("hureeyyyyyyyyy") 
print("are you happy") 
print("😉 stay happy")
print("special thanks to github")
